services:
  backend:
    image: falcozerk/chargeweave-backend:latest
    build:
      context: backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db.chargeweave.com:3306/chargeweave?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: chargeweave
      SPRING_DATASOURCE_PASSWORD: cellar-sauna-GENERA
    networks:
      - backend
      - web

  web:
    image: falcozerk/chargeweave-web:latest
    build:
      context: web
      args:
        REACT_APP_API_BASE_URL: http://127.0.0.1:8080/api
    ports:
      - "9090:80"
    depends_on:
      - backend
    networks:
      - web

#  db:
#    image: mysql:5.7
#    ports:
#      - "3306:3306"
#    restart: always
#    environment:
#      MYSQL_DATABASE: chargeweave
#      MYSQL_USER: chargeweave
#      MYSQL_PASSWORD: yas81moq
#      MYSQL_ROOT_PASSWORD: vra90dal
#    volumes:
#      - mysql:/var/lib/mysql
#    networks:
#      - backend

#volumes:
#  mysql:

networks:
  backend:
  web: